# MoveIt-specific simulation settings
moveit_sim_hw_interface:
  joint_model_group: manipulator
  joint_model_group_pose: up
  cycle_time_error_threshold: 0.01
# Settings for ros_control control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  name: manipulator_controller
  joints:
    - joint_s
    - joint_l
    - joint_e
    - joint_u
    - joint_r
    - joint_b
    - joint_t
  name: hand_controller
  joints:
    - sia20d_finger_joint1
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
# Joint Trajectory Controller
# For detailed explanations of parameter see http://wiki.ros.org/joint_trajectory_controller
position_trajectory_controller:
  type: position_controllers/JointTrajectoryController
  name: manipulator_controller
  joints:
    - joint_s
    - joint_l
    - joint_e
    - joint_u
    - joint_r
    - joint_b
    - joint_t
  name: hand_controller
  joints:
    - sia20d_finger_joint1
  constraints:
    goal_time: 5.0
    name: manipulator_controller
    joints:
      - joint_s:
          trajectory: 0.60
          goal: 0.15
      - joint_l:
          trajectory: 0.60
          goal: 0.15
      - joint_e:
          trajectory: 0.60
          goal: 0.15
      - joint_u:
          trajectory: 0.60
          goal: 0.15
      - joint_r:
          trajectory: 0.60
          goal: 0.15
      - joint_b:
          trajectory: 0.60
          goal: 0.15
      - joint_t:
          trajectory: 0.60
          goal: 0.15
    name: hand_controller
    joints:
      - sia20d_finger_joint1:
          trajectory: 0.60
          goal: 0.15
# Group Position Controllers  # Allows to send single ROS msg of Float64MultiArray to all joints
joint_position_controller:
  type: position_controllers/JointGroupPositionController
  name: manipulator_controller
  joints:
    - joint_s
    - joint_l
    - joint_e
    - joint_u
    - joint_r
    - joint_b
    - joint_t
  name: hand_controller
  joints:
    - sia20d_finger_joint1